# Generated by Django 5.2.7 on 2025-10-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_rename_fecha_pago_creado_rename_total_pago_monto_and_more'),
        ('pedidos', '0004_alter_pedido_direccion_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20),
        ),
    ]
