# Generated by Django 5.2.7 on 2025-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_fecha_pedido_creado_pedido_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.TextField(blank=True, default='Sin dirección registrada', null=True),
        ),
    ]
